---
title: "run mplus machines as participants model"
author: "andrew demetriou"
---

```{r setup, include=FALSE}
library('here')            # file logistics
library('data.table')      # data manipulation
library('dplyr')           # data manipulation
library("MplusAutomation") # Mplus integration

# load datasets
machines_as_subjects_df <- readRDS(here("VI_data_collection", "_data", "machine_response_data", "machines_as_subjects_df.RDS"))

values <- c("POWER", "ACHIEVEMENT", "HEDONISM", 
            "STIMULATION", "SELF", "UNIVERSALISM", 
            "BENEVOLENCE", "TRADITION", 
            "CONFORMITY", "SECURITY")
```


```{r}
# select only ID columns and values scores
df <- machines_as_subjects_df %>% select(row_number, participant_ID, item_ID, all_of(values))

# rename columns to have same names as in functions
colnames(df) <- c("row_number", "subject_ID", "item_ID", paste0("y", seq(1, 10)))
df <- as.data.frame(df)

rm(machines_as_subjects_df)
```

```{r}
# run mplus model
# load mplus model
source(here("VI_data_collection", "2_intermediary_data_computing", "_mplus_models", "participant_model_1.0.R"))

 fit <- mplusModeler(mplus_model, 
                     modelout = "VI_data_collection/_data/mplus_output/sim.inp", 
                     run=TRUE)

# print errors and warnings
 fit$results$errors
 fit$results$warnings

saveRDS(fit, here("VI_data_collection", "_data", "intermediary_data", "m_mplus_participant_model_1.0.RDS"))
```


