---
title: "3_fix_NA_values"
author: "Andrew M. Demetriou"
date: "2023-04-06"
output: html_document
---

```{r}
library('here')
library('data.table')
library('dplyr')
library('stringr')
```


```{r}
source(here("VI_data_collection_november_2022", 'scripts', '2_fix_column_names_1.0.R'))
```

```{r}
# make a temp dataframe
ids <- all_dt[174:191, 1]
temp_df <- all_dt[174:191, 29:64]
temp_df$PROLIFIC_PID <- ids
temp_df <- temp_df |> select(PROLIFIC_PID, everything())
rm(ids)
```

```{r}
# character vector of relevant column names
cols <- temp_df |> select(contains(c(
  "-w", "-f", "1_1", "1_2", "1_3", "1_4", "1_5", 
  "1_6", "1_7", "1_8", "1_9", "1_10", "m_", "-c"
  ))) |> colnames()

# convert columns to numeric, blanks to NA
temp_df[,cols] <- lapply(cols, function(x)as.numeric(temp_df[[x]]))
```

```{r}
for(col in 1:ncol(temp_df)){
  if(grepl("-w", colnames(temp_df[,..col]))==T){
    
    mxm_id <- temp_df[,..col] |>
            colnames() |>
            word(1, sep = "-")
    
    print(mxm_id)
  }
}

```
```{r}
for(row in 1:nrow(temp_df)){
  for(col in 1:ncol(temp_df)){
    
    
    if(is.na(temp_df[row, ..col])==F){
      paste0(temp_df[row, 1], " completed ", colnames(temp_df[, ..col])) |>
        print()
      
      }
  }
}
```

```{r}
for(row in 1:nrow(temp_df)){
  for(col in 1:ncol(temp_df)){
    if(grepl("-w", colnames(temp_df[,..col]))==T){
      if(is.na(temp_df[row, ..col])==F){
        
        #paste0(temp_df[row, 1], " completed ", colnames(temp_df[, ..col])) |>
        #print()
        
        #print(colnames(temp_df[row, seq(2,11)+col, with=FALSE]))
        
       temp_df[row, seq(1,11)+col] <- setnafill(
         temp_df[row, seq(1,11)+col, with=FALSE], fill=0)
        
        
      
   }
  }
 }
}
```

```{r}
#make a bigger temp dataframe
ids <- all_dt[, 1]
temp_df <- all_dt[, 29:64]
temp_df <- temp_df |> select(PROLIFIC_PID, everything())
rm(ids)
```

