---
title: "random effects estimated with lmer and mplus"
author: "andrew demetriou"
---

```{r setup, include=FALSE}
library('here')            # file logistics
library('data.table')      # data manipulation
library('dplyr')           # data manipulation
library('tidyr')           # data manipulation
library("MplusAutomation") # Mplus integration
library("boot")            # bootstrapping CIs
library('ggplot2')         # visualization

# load dataset
source(here("VI_data_collection_november_2022", "functions", "load_and_format_data_1.0.R"))

options(scipen=999)
theme_set(theme_minimal())
```


```{r}
# load lme4 functions
source(here("VI_data_collection_november_2022", "functions", "lme4_descriptives_function_1.7.R"))

# load mplus functions
source(here("VI_data_collection_november_2022", "functions", "mplus_descriptives_function_1.5.R"))
```

```{r}
# select only ID columns and values scores
df <- responses_dt %>% select(row_number, participant_ID, item_ID, all_of(values))

# rename columns to have same names as in functions
colnames(df) <- c("row_number", "subject_ID", "item_ID", values)

rm(responses_dt)
```

```{r}
# format df for mplus:
# rename columns to have same names as in functions
colnames(df) <- c("row_number", "subject_ID", "item_ID", paste0("y", seq(1, 10)))

# mplus and data.table don't work together
df <- as.data.frame(df)
```



https://www.lesahoffman.com/PSYC943/Introduction_to_Mplus_Syntax.pdf

I could enter an arbitrary 'IDVARIABLE', and include it in the 'AUXILIARY' section. 

```{r}
# mplus model specification:
# this model estimates parameters from response data 
# including the correlation of the item intercepts

mplus_model <- mplusObject(
  TITLE = "model;",
  MISSING = ".;",
  # select only participant variables
  VARIABLE = "
  USEVARIABLES = item_ID subject_ID y1-y10 item_number;
  CLUSTER = item_ID subject_ID;
  IDVARIABLE = row_number;
  AUXILIARY = item_number;",
  
  # the only estimator available is Bayes
  # manual page 656:
  # FBITERATIONS: number of iterations for each MCMC chain
  ANALYSIS = "
  TYPE = CROSSCLASSIFIED RANDOM;
  ESTIMATOR = BAYES;
  FBITERATIONS = 10000;
  ALGORITHM = GIBBS(RW);
  PROCESSORS = 11;",
  
  MODEL = "
  
  %within% 
  y1-y10;
  
  %between item_ID% 
  y1-y10; [y1-y10];  
  y1 WITH y1-y10;
  y2 WITH y1-y10;
  y3 WITH y1-y10;
  y4 WITH y1-y10;
  y5 WITH y1-y10;
  y6 WITH y1-y10;
  y7 WITH y1-y10;
  y8 WITH y1-y10;
  y9 WITH y1-y10;
  y10 WITH y1-y10;
  
  %between subject_ID% 
  y1-y10; [y1-y10@0];", 
  
  OUTPUT = "standardized cinterval(hpd)",
  
  # page 838 of the manual:
  # distribution of plausible values for each observation
  # first number in fscores is the number of draws to compute per observation
  # from a bayesian estimation procedure;
  # when second number in fscores is ten, every tenth draw is used to compute 
  SAVEDATA = "FILE IS fscores.dat;
              Save = fscores(100 10);",
  
  rdata = df
)

# run mplus model
fit <- mplusModeler(mplus_model, 
                    modelout = "mplus/sim.inp", 
                    run=TRUE)
# print errors and warnings
 fit$results$errors
 fit$results$warnings

#saveRDS(fit, here("VI_data_collection_november_2022", "intermediary_data", "participant_model_1.0.RDS"))
 
rm(mplus_model)
```

```{r}
# mplus model specification:
# this model estimates parameters from response data 
# including the correlation of the item intercepts

mplus_model <- mplusObject(
  TITLE = "model;",
  MISSING = ".;",
  # select only participant variables
  VARIABLE = "
  USEVARIABLES = item_ID subject_ID y1-y10;
  CLUSTER = item_ID subject_ID;
  IDVARIABLE = row_number;",
  
  # the only estimator available is Bayes
  # manual page 656:
  # FBITERATIONS: number of iterations for each MCMC chain
  ANALYSIS = "
  TYPE = CROSSCLASSIFIED RANDOM;
  ESTIMATOR = BAYES;
  FBITERATIONS = 10000;
  ALGORITHM = GIBBS(RW);
  PROCESSORS = 11;",
  
  MODEL = "
  
  %within% 
  y1-y10;
  
  %between item_ID% 
  y1-y10; [y1-y10];  
  y1 WITH y1-y10;
  y2 WITH y1-y10;
  y3 WITH y1-y10;
  y4 WITH y1-y10;
  y5 WITH y1-y10;
  y6 WITH y1-y10;
  y7 WITH y1-y10;
  y8 WITH y1-y10;
  y9 WITH y1-y10;
  y10 WITH y1-y10;
  
  %between subject_ID% 
  y1-y10; [y1-y10@0];", 
  
  OUTPUT = "standardized cinterval(hpd)",
  
  # page 838 of the manual:
  # distribution of plausible values for each observation
  # first number in fscores is the number of draws to compute per observation
  # from a bayesian estimation procedure;
  # when second number in fscores is ten, every tenth draw is used to compute 
  SAVEDATA = "FILE IS fscores.dat;
              Save = fscores(100 10);",
  
  rdata = df
)

# run mplus model
fit <- mplusModeler(mplus_model, 
                    modelout = "mplus/sim.inp", 
                    run=TRUE)
# print errors and warnings
 fit$results$errors
 fit$results$warnings

#saveRDS(fit, here("VI_data_collection_november_2022", "intermediary_data", "participant_model_1.0.RDS"))
 
rm(mplus_model)
```


```{r}
t <- fit$results$savedata

s<- merge(df, t, by.x='row_number', by.y = 'ROW_NUMB')

s <- s %>% select(subject_ID, SUBJECT_ID, item_ID, ITEM_ID, all_of(everything()))

s %>% arrange(as.numeric(item_ID))

cor(s$y1, s$Y1)
```

```{r}
# retrieve item intercepts from mplus model fscores output:
mplus_intercept_df <- get_random_intercepts_mplus(fit, intercept = 'item_ID')

# format table
mplus_intercept_df <- mplus_intercept_df %>% 
  pivot_longer(cols = all_of(values), names_to = "value", values_to = "intercept") %>%
  arrange(value, ITEM_ID)
  

# save object
 #save(mplus_intercept_df, file = here("VI_data_collection_november_2022", "intermediary_data", "mplus_intercept_df.RDS"))

#load(here("VI_data_collection_november_2022", "intermediary_data", "mplus_intercept_df.RDS"))
```


Double checking MPLUS output:

```{r}
# check that means in mplus output match means extracted from fscores

fit <- readRDS(here("VI_data_collection_november_2022", "intermediary_data", "participant_model_1.0.RDS"))

# retrieve item intercepts from mplus model fscores output:
item_intercepts <- get_random_intercepts_mplus(fit, intercept = 'item_ID')

# compute mean of item intercepts
# in simulated data these were set to 0
item_intercept_summary_df <-  item_intercepts %>%
  select(-ITEM_ID) %>%
  colMeans() %>%
  t() %>%
  as.data.frame() |>
  t() |>
  as.data.frame() |>
  rownames_to_column() |>
  rename('mean' = 'V1', 'values' = 'rowname') 

model_output_means <- fit$results$parameters$unstandardized |>
  filter(BetweenWithin == "Between ITEM_ID") |>
  filter(paramHeader == "Means") |>
  select(-paramHeader, -sig, -BetweenWithin)

model_output_means |> 
  ggplot(aes(x = values, y= est, color = values)) +
    geom_point() +
    geom_errorbar(aes(ymin=lower_2.5ci, ymax=upper_2.5ci)) + 
    geom_hline(yintercept = 0, linetype = 'dotted', color = 'red') +
    # plot the means extracted from the fscores file as a red 'x' (item_intercepts_summary_df)
    geom_point(data = item_intercept_summary_df, aes(x=values, y=mean, color = "red"), shape = 4, size = 4) +
    theme_minimal() +
    theme(legend.position = "none", axis.text.x = element_text(angle = 45)) +
    ggtitle("item intercept mean by value")
```