---
title: "item analysis"
author: "andrew demetriou"
---

```{r setup, include=FALSE}
library('here')            # file logistics
library('data.table')      # data manipulation
library('dplyr')           # data manipulation
library('tidyr')           # data manipulation
library('ggplot2')         # visualization
library('ggridges')        # joyplot visualization
library('shiny')           # interactive visualization
library('Rtsne')           # tsne visualization

options(scipen=999)
theme_set(theme_minimal())
```

```{r}
# load dataset
load(here("VI_data_collection_november_2022", "intermediary_data", "public_df.RDS"))

# create a working dataset
responses_dt <- as.data.table(public_df)

rm(public_df)
```


```{r}
# replace 'song' with 'item_ID' as column name
setDT(responses_dt)

# subset columns for values questions:
responses_dt <- responses_dt %>%
  select("participant_ID", "item_ID", "w", "f", 
         paste0("1_", seq(1, 10)),
         "c")

# convert to numeric
columns <- c(paste0("1_", seq(1, 10)), "c")
responses_dt[, (columns):= lapply(.SD, as.numeric), .SDcols = columns]

responses_dt <- responses_dt %>%
  rename(writer=w, 
         familiar = f, 
         POWER = `1_1`, 
         ACHIEVEMENT = `1_2`, 
         HEDONISM = `1_3`, 
         STIMULATION = `1_4`, 
         SELF = `1_5`, 
         UNIVERSALISM = `1_6`, 
         BENEVOLENCE = `1_7`, 
         TRADITION = `1_8`, 
         CONFORMITY = `1_9`, 
         SECURITY = `1_10`, 
         confidence = c
         ) %>%
  select(participant_ID, item_ID, 
                         POWER, ACHIEVEMENT, HEDONISM, 
                         STIMULATION, SELF, UNIVERSALISM, 
                         BENEVOLENCE, TRADITION, 
                         CONFORMITY, SECURITY, 
                         writer, familiar, confidence)


values<-c("POWER", "ACHIEVEMENT", "HEDONISM",  
          "STIMULATION", "SELF", "UNIVERSALISM", 
          "BENEVOLENCE", "TRADITION",  
          "CONFORMITY", "SECURITY")

rm(columns)
```


```{r}
responses_dt %>%
  pivot_longer(cols = POWER:SECURITY) %>%
  ggplot(aes(x=value, group=name, col = name)) +
  geom_density()
```

```{r}
tsne <- 
  responses_dt[,3:12] %>%
  Rtsne(., dims=2, check_duplicates = F, perplexity=50, verbose=TRUE, max_iter=500, pca = T)

tsne_df <- tsne$Y %>% as.data.frame()

tsne_df$item_ID <- responses_dt$item_ID
```

```{r}
tsne_df %>%
  ggplot(aes(x=V1, y=V2, color = item_ID)) +
  geom_point(size = 0.1) +
  theme(legend.position = 'none')
```


Make a list of plots to display the value ratings for each song:

```{r}
item_plot_dt <- responses_dt

# convert to long format
item_plot_dt <- as.data.table(item_plot_dt) %>% 
  melt(., id.vars = c("participant_ID", "item_ID"), 
       measure.vars = c("ACHIEVEMENT","BENEVOLENCE", "CONFORMITY", "HEDONISM", "POWER", "SECURITY", "SELF", "STIMULATION", "TRADITION", "UNIVERSALISM"))


# make a character vector of all song IDs
items <- unique(item_plot_dt$item_ID)

# make a function to plot all the value ratings for each song
item_plot_function <- function(item_plot_dt, item){
  item_plot_dt %>% filter(., item_ID == item) %>%
    ggplot(., aes(x=value, y=variable, fill = 0.5 -abs(0.5 -stat(ecdf)))) +
    stat_density_ridges(geom="density_ridges_gradient", calc_ecdf=TRUE, show.legend=FALSE) +
    scale_fill_viridis_c(option="C") +
    theme_minimal() +
    xlab("")
}

# make a list of plots, one for each song
list_of_song_by_value_plots <- lapply(items, function(i) item_plot_function(item_plot_dt, i))

#name each plot after the song item it represents
names(list_of_song_by_value_plots) <- items

#list_of_song_by_value_plots[201]
rm(item_plot_function, item_plot_dt)
```

Make a plot of the confidence scores for each song:

```{r}
#compute median
median_confidence <- responses_dt %>% group_by(item_ID) %>% summarize(median=median(confidence, na.rm=TRUE))

#plot histogram of individual song's confidence ratings
plot_confidence <- function(item){
  
  #item <- items[200]
  #median_confidence %>% filter(item_ID == item) %>% .$median
  
  responses_dt %>% filter(., item_ID == item) %>%
    ggplot(aes(confidence)) +
    geom_histogram(color = 'black', fill = 'grey', bins=10)+
    geom_vline(xintercept  = median_confidence %>% filter(., item_ID == item)%>% .$median, color = 'red') + 
    ylab("") +
    xlab("Self reported Confidence in Ratings") +
    theme(legend.position = 'none')
}

#make list of confidence histograms
list_of_confidence_plots <- lapply(items, plot_confidence)

#name each plot in list after the item they represent
names(list_of_confidence_plots) <- items

rm(median_confidence, plot_confidence)
```


Dynamic display of results:

```{r}
ui <- fluidPage(
  titlePanel("Distribution of Ratings per Value by Song"),
  
  # drop down menu to display the values
  selectInput('choice', 'select song', choice = items), 
  
  #plot song plot
  plotOutput('song_by_value_plots'),
  
  #plot confidence ratings
  plotOutput('confidence_plot')
  
)

server <- function(input, output, session){
  
  # write a function that receives the input
  # and then filters dataframe column
  display_summary <- function(dt) {
    dt %>% select(stat, item_ID, input$choice)
  }
  
  # render the plots; alpha distribution by n
  output$song_by_value_plots <- renderPlot({
      #note that plots are pre-computed
      list_of_song_by_value_plots[input$choice]
  })
  
  output$confidence_plot <- renderPlot({
    list_of_confidence_plots[input$choice]
  })
  
  
  }
shinyApp(ui=ui, server=server)
```
```{r}
rm(confidence_dt, list_of_confidence_plots, list_of_song_by_value_plots, median_confidence, ui, server, plot_confidence, cols, confidence_ratings, data_file_path, file_name, items, values)
```