---
title: "machine data import"
author: "Andrew M. Demetriou"
---

#AIM: Import and format machine scores data provided extracted from:
https://replicate.com/eldrin/text-concept-similarity

```{r}
library('here')         # file logistics
library('data.table')   # read in data
library('tidyverse')    # data logistics
```

```{r}
# get song ids
mxm_ids <- readRDS(here("VI_data_collection", "_data", "primary_data", "mxm_ids"))
```

```{r}
# create list of machine output file names
path <- here("VI_data_collection", "_data", "machine_scores", "second_export")
files <- list.files(path)
```

```{r}
# create list of read in files
machines_as_subjects <- lapply(files, function(x){
  # read in file
  df <- fread(input = here(path, x))
  # create machine ID column, remove file extension
  df$machine_ID <- gsub("\\..*","",x)
  # rename song id column
  df$song_id <- mxm_ids
  # reorder columns
  df <- df %>% select(machine_ID, song_id, all_of(everything()))
  return(df)
})

# turn list into a single data.table
machines_as_subjects <- rbindlist(machines_as_subjects)
# transform to character column
machines_as_subjects$song_id <- as.character(machines_as_subjects$song_id)
```


```{r}
# remove extra song
machines_as_subjects <- machines_as_subjects %>% filter(V1 != '360')

# remove V1 column
machines_as_subjects <- machines_as_subjects %>% select(-V1)

# add row number for syncing with Mplus output
machines_as_subjects$row_number <- seq(1:nrow(machines_as_subjects))

# rename columns
colnames(machines_as_subjects) <- c("participant_ID", "item_ID", 
                                    "SECURITY", "CONFORMITY", "TRADITION", 
                                    "BENEVOLENCE", "UNIVERSALISM", "SELF", 
                                    "STIMULATION", "HEDONISM", 
                                    "ACHIEVEMENT", "POWER", "row_number"
                                    )

# reorder columns
machines_as_subjects <- machines_as_subjects %>% 
    select(row_number, participant_ID, item_ID, 
         POWER, ACHIEVEMENT, HEDONISM, 
         STIMULATION, SELF, UNIVERSALISM, 
         BENEVOLENCE, TRADITION, 
         CONFORMITY, SECURITY)
```

```{r}
saveRDS(machines_as_subjects, file = here("VI_data_collection", "_data", "machine_response_data", "machines_as_subjects_df_2.0.RDS"))
write_csv(machines_as_subjects, file = here("VI_data_collection", "_data", "machine_response_data", "machines_as_subjects_df_2.0.csv"))
```

