---
title: "4_check_duplicates"
author: "Andrew M. Demetriou"
date: "2023-04-06"
output: html_document
---

```{r}
library('here')
library('data.table')
library('dplyr')
library('stringr')
library('tidyr')
#library('janitor')

source(here("VI_data_collection_november_2022", 'scripts', '2_fix_column_names_1.0.R'))
```


```{r}
t <- temp_df |> 
  
  # pivot longer had an issue with mixed column types
  # make everything a character vector
  mutate(across(everything(), as.character)) |>
  
  # pivot to long format
  pivot_longer(
    
    # range of columns
    #cols = `828136-w`:`1027136-r`, 
    cols = `828136-w`:`2107983-r`, 
  
    # two new columns: song and question
    names_to = c('song', 'question'),
  
    # separate names by "-"
    names_sep = "-", 
  
    # new columns for participant responses
    values_to = "response", 
  
    # drop empty cells
    values_drop_na = TRUE
)

```

```{r}
# check for duplicates
  t %>%
  #dplyr::group_by(PROLIFIC_PID, song, question) %>%
  dplyr::group_by(ResponseId, song, question) %>%
  dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
  dplyr::filter(n > 1L)

# 639dc966f953a42bc397c24b appears twice in the records
```


```{r}
s <- t|> 
  pivot_wider(
    names_from = question, 
    values_from = response
  )
```

```{r}
which(duplicated(names(all_dt)))

all_dt[, 2082]
all_dt[, 4272]
all_dt[, 4273]
all_dt[, 4274]

dput( head( all_dt, 0 ) )


#duplicates <- all_dt |>
#  filter(PROLIFIC_PID == "639dc966f953a42bc397c24b")

dupe <- all_dt[PROLIFIC_PID == "639dc966f953a42bc397c24b"]
```

