---
title: "Subjectivity"
author: "andrew demetriou"
date: "26/04/2023"
---

#AIM

In this notebook, I examine the responses to questions that asked about the overall subjectivity of the task, the overall rater confidence, and at the open response format 'feedback' fields.

```{r}
library('data.table') # data manipulation
library('dplyr')      # data manipulation
library('tidyverse')  # data manipulation
library('here')       # file logistics
library('ggplot2')    # visualization
library('viridis')    # visualization colors
library('ggridges')   # joyplots
library('wordcloud')  # wordclouds
library('tm')         # wordclouds dependency
library('tidytext')

options(scipen=999)
theme_set(theme_minimal())
```

```{r}
# load dataset
load(here("VI_data_collection_november_2022", "intermediary_data", "working_df.RDS"))

# create a working dataset
responses_dt <- as.data.table(working_df)

rm(working_df)
```

```{r}
# make missing data explicitly NA
for(i in names(responses_dt[,participant_ID:Finished])) (set(responses_dt, which(responses_dt[[i]] == "DATA_EXPIRED"), i, NA))
rm(i)
# replace missing values with NA
responses_dt[Sex=="CONSENT_REVOKED"] <- NA

# not sure what this is meant to indicate
# treat as missing
responses_dt[Age=="1022"] <- NA
```

```{r}
subjectivity <- responses_dt[,c('participant_ID', 'subjective')] %>% unique()
```

People overall found this to be a subjective task, with the modal rating being "Very subjective". 

```{r}
subjectivity |>
  ggplot(aes(x=as.numeric(subjective))) +
  geom_histogram(binwidth=1, color = 'grey',fill = "orange") +
  scale_x_continuous(
       position = "top",
       breaks = seq(1, 7, by = 1),
       labels = c(
       "Completely subjective",
       "Very subjective", 
       "Somewhat subjective", 
       "Neither subjective nor objective", 
       "Somewhat objective", 
       "Very objective", 
       "Completely objective"
       )
  ) +
  stat_bin(binwidth=1,geom='text', aes(label=..count..), 
           position=position_stack(vjust=1)) +
  coord_flip() +
  #theme_minimal() +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank())

#rm(subjectivity)
```



