---
title: "Subjectivity"
author: "andrew demetriou"
date: "26/04/2023"
---

#AIM

In this notebook, I examine the responses to questions that asked about the overall subjectivity of the task, the overall rater confidence, and at the open response format 'feedback' fields.

```{r}
library('data.table') # data manipulation
library('dplyr')      # data manipulation
library('tidyverse')  # data manipulation
library('here')       # file logistics
library('ggplot2')    # visualization
library('tidytext')   # text processing
library('wordcloud')  # wordclouds
library('tm')         # wordclouds dependency

options(scipen=999)
theme_set(theme_minimal())
```

```{r}
# load dataset
load(here("VI_data_collection_november_2022", "intermediary_data", "working_df.RDS"))

# create a working dataset
responses_dt <- as.data.table(working_df)

rm(working_df)
```

```{r}
# make missing data explicitly NA
for(i in names(responses_dt[,participant_ID:Finished])) (set(responses_dt, which(responses_dt[[i]] == "DATA_EXPIRED"), i, NA))
rm(i)
# replace missing values with NA
responses_dt[Sex=="CONSENT_REVOKED"] <- NA

# not sure what this is meant to indicate
# treat as missing
responses_dt[Age=="1022"] <- NA
```

```{r}
# create a df of subjectivity scores
subjectivity <- responses_dt[,c('participant_ID', 'subjective')] %>% unique()
```

```{r}
# frequency table
subjectivity_table <- subjectivity |>
  group_by(subjective) |>
  filter(!is.na(subjective)) |>
  count()

# percentage for each response
subjectivity_table$proportion <- subjectivity$subjective |>
  as.numeric() |>
  table() |>
  prop.table()

# ~ 86% somewhat subjective or more
subjectivity_table[1:3,3] |> sum()

# ~ 63% very subjective or more
subjectivity_table[1:2,3] |> sum()

# ~ 43% very subjective
subjectivity_table[2:2,3] |> sum()

rm(subjectivity_table)
```


People overall found this to be a subjective task, with the modal rating being "Very subjective". 

```{r}
# plot histogram
subjectivity |>
  ggplot(aes(x=as.numeric(subjective))) +
  geom_histogram(binwidth=1, fill = "orange") +
  scale_x_continuous(
       position = "top",
       breaks = seq(1, 7, by = 1),
       labels = c(
       "Completely subjective",
       "Very subjective", 
       "Somewhat subjective", 
       "Neither subjective nor objective", 
       "Somewhat objective", 
       "Very objective", 
       "Completely objective"
       )
  ) +
  stat_bin(binwidth=1,geom='text', aes(label=..count..), 
           position=position_stack(vjust=0.8)) +
  coord_flip() +
  theme_minimal() +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank())

rm(subjectivity)
```

```{r}
feedback <- responses_dt %>%
  select(participant_ID, feedback) %>%
  unique() %>%
  .[!is.na(feedback)]

feedback$feedback <- feedback$feedback |> tolower()

tidy_open_responses <- feedback %>%
  unnest_tokens(word, feedback) %>%
  anti_join(get_stopwords()) %>% 
  count(word, sort = TRUE) 

wordcloud(tidy_open_responses$word, tidy_open_responses$n, max.words = 150)
```





```{r}
# remove some obviously uninformative responses
confidence_open_responses_dt <- confidence_open_responses_dt %>%
  .[!r=="no"] %>%
  .[!r=="n"] %>%
  .[!r==" no"] %>%
  .[!r=="no "] %>%
  .[!r=="no."] %>%
  .[!r=="n o"] %>%
  .[!r=="n0"] %>%
  .[!r=="yes"] %>%
  .[!r==" yes"] %>%
  .[!r=="yes "] %>%
  .[!r=="?"] %>%
  .[!r=="n/a"] %>%
  .[!r=="na"] %>%
  .[!r=="not really"] %>%
  .[!r=="nothing"] %>%
  .[!r=="none"] %>%
  .[!r=="none."]
```

```{r}
tidy_open_responses <- confidence_open_responses_dt %>%
  unnest_tokens(word, r)

tidy_open_responses <- tidy_open_responses %>% 
  anti_join(get_stopwords()) %>% 
  count(word, sort = TRUE) 
  
wordcloud(tidy_open_responses$word, tidy_open_responses$n, max.words = 150)

rm(confidence_open_responses_dt, tidy_open_responses)
```


```{r}
# select columns to keep: 'c' indicates the confidence ratings
confidence_ratings_dt <- responses_dt |> select(participant_ID, song, c)
```

Participants mostly responded with `Somewhat confident` across all lyrics. 

```{r}
confidence_ratings_dt %>%
  ggplot(aes(x=as.numeric(c))) +
  geom_histogram(bins=100)
```
