---
title: "machine dimension exploration"
---

```{r}
library('here')            # file logistics
library('data.table')      # data manipulation
library('tidyverse')       # data manipulation
library("psych")           # factor analysis
library("ggplot2")         # visualization
library("corrplot")        # correlation plot
library('FactoMineR')      # extracting principal components
library('factoextra')      # visualization

# load dfs
machines_as_subjects <- readRDS(here("VI_data_collection", "_data", "machine_response_data", "machines_as_subjects_df.RDS"))

values <- c("POWER", "ACHIEVEMENT", "HEDONISM", 
            "STIMULATION", "SELF", "UNIVERSALISM", 
            "BENEVOLENCE", "TRADITION", 
            "CONFORMITY", "SECURITY")

# pivot to wide format
machines_as_fixed_dfs <- lapply(machines_as_subjects, function(df){
  df %>%
    pivot_wider(id_cols = item_ID, 
                names_from = participant_ID, 
                values_from = all_of(values))
})
```

```{r}
build_factor_loadings_df <- function(machines_as_fixed_df, n_factors=1){
  
  
  # run factor analyses and store as list
  machine_fas <- lapply(values, function(x){
  machines_as_fixed_df %>% select(starts_with(x)) %>%
    fa(nfactors=n_factors, fm="ml")
  })
  
  # extract factor loadings as a list, format as data.table
  machine_loadings_list <- lapply(machine_fas, function(x){
    df <- x$loadings[1:44,] %>% as.data.frame()
    df$participant_ID <- rownames(df)
    rownames(df) <- NULL
    #colnames(df) <- c("loadings", "participant_ID")
    setDT(df)
    return(df)
  })

  # bind list into a single data.table
  machine_loadings_df <- rbindlist(machine_loadings_list)

  # create a new column for each value
  lapply(values, function(x){
    machine_loadings_df[grepl(x, machine_loadings_df$participant_ID), value := x]
  })

  # remove value name from participant_ID column
  for(value in values){
    machine_loadings_df$participant_ID <- gsub(paste0(value, "_"), "", machine_loadings_df$participant_ID)
  }

  machine_loadings_df$participant_ID <- gsub("_weight_lyrics", "", machine_loadings_df$participant_ID)
  machine_loadings_df$participant_ID <- gsub("mxm_", "", machine_loadings_df$participant_ID)

  return(machine_loadings_df)

}
```

```{r}
plot_factor_loadings <- function(df){
  df %>%
    ggplot(aes(participant_ID, abs(.), fill = .)) +
    facet_wrap(~value, nrow=1) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_gradient2(name = "Loading", 
                         high = "blue", mid = "white", low = "red", 
                         midpoint = 0, guide = "none") +
    ylab("loading") +
    theme_bw(base_size =10) +
    theme(axis.text.x= element_text(angle = 90))
}
```

```{r}
factor_1_df <- build_factor_loadings_df(machines_as_fixed_df = machines_as_fixed_dfs[[4]], n_factors = 1)

plot_factor_loadings(factor_1_df)
```


```{r}
show_correlation_plot <- function(df=machines_as_fixed_dfs[[4]], value="POWER"){
  df <- df %>% select(any_of(starts_with(value)))
  cor_mat <- cor(df)
  rownames(cor_mat) <- NULL
  colnames(cor_mat) <- NULL
  corrplot(cor_mat, title = value)
}
```

```{r}
for(value in values){
  show_correlation_plot(value=value)
}
```
